### ISSUE TITLE
deeplabv3-segmap

### ISSUE THREAD

**Issue by SarchWu** [lijiancheng0614/lijiancheng0614.github.io#1]
博主好，我按照您的博客https://lijiancheng0614.github.io/2018/03/13/2018_03_13_TensorFlow-DeepLab/#disqus_thread中提到的步骤进行了deeplabv3的训练，可视化以及测试，目前是可以在plt中可视化检测结果的。但是我在查看segmap的shape时候，segmap的尺寸为256*513，与我训练的尺寸cropsize设置不符。想请教一下是什么地方存在问题么？谢谢答复

**Comment by lijiancheng0614** [comment]
训练的时候设置了 `train_crop_size`，因此进行了 crop 吧。可以看看 `train.py` 里是怎么 crop 的

**Comment by SarchWu** [comment]
博主好，我刚才仔细看了train.py和我训练的指令。指令里面已经设置了和训练数据一样的尺寸。出现segmap尺寸为256*513的原因是在进行prediction的时候，有INPUT_SIZE这个参数的设置，这个关系到投入网络预测的图片相对segmap的比例。所以就会导致和训练时的数据尺寸不符的问题。现已修改input_size并解决该问题。谢谢博主，您的博客逻辑很清晰，步骤细致，十分有帮助。
